version: "{build}"
build: off
skip_tags: true
sudo: required
environment:
  matrix:
    - nodejs_version: "6"
platform:
  - x86
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - ps: |
        $apps=Get-WmiObject -Class Win32_Product | Where-Object {$_.Name -match ".NET Framework 4.6"}
        foreach ($app in $apps) {
          $app.Uninstall()
        }
  - set PATH=%APPDATA%\npm;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%
  - npm install --ignore-scripts
  - npm run build
  - npm run install -- --verbose --force

test_script:
  - npm test
