version: "{build}"
build: off
skip_tags: true

environment:
  matrix:
    - nodejs_version: "6"

platform:
  - x86

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - ps: $apps=Get-WmiObject -Class Win32_Product | Where-Object {$_.Name -match ".NET Framework 4.6" -or $_.Name -match "Build Tools"}
        foreach ($app in $apps) {
          $app.Uninstall()
        }
  - set PATH=%APPDATA%\npm;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%
  - npm install --ignore-scripts
  - npm run build
  - npm run install
  - for /f %%i in ('node -v') do set exact_nodejs_version=%%i
  # - prebuild -b %exact_nodejs_version% --strip

test_script:
  - npm test
